<a href="https://colab.research.google.com/github/JapiKredi/SelfAttention/blob/main/SelfAttention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [1]:
import numpy as np

def self_attention(input_sequence):
    # Assume input_sequence is a 2D array where each row represents a token embedding

    # Step 1: Calculate Query, Key, and Value matrices
    Q = np.dot(input_sequence, W_q)  # Transform input embeddings to Query space
    K = np.dot(input_sequence, W_k)  # Transform input embeddings to Key space
    V = np.dot(input_sequence, W_v)  # Transform input embeddings to Value space

    # Step 2: Calculate attention scores
    scores = np.dot(Q, K.T) / np.sqrt(d_k)  # Scaled dot product attention
    attention_weights = softmax(scores, axis=1)  # Apply softmax to obtain attention weights

    # Step 3: Apply attention weights to Value vectors
    attention_output = np.dot(attention_weights, V)  # Weighted sum of Value vectors

    return attention_output

In [2]:
# Example input sequence (3 tokens, each represented by a 4-dimensional vector)
input_sequence = np.array([[1, 2, 3, 4],
                           [2, 3, 4, 5],
                           [3, 4, 5, 6]])


In [3]:
# Example weight matrices (learnable parameters)
W_q = np.random.randn(4, 4)  # Query matrix
W_k = np.random.randn(4, 4)  # Key matrix
W_v = np.random.randn(4, 4)  # Value matrix

In [4]:
# Dimension of Key and Query vectors
d_k = W_q.shape[1]

In [5]:
# Softmax function
def softmax(x, axis=-1):
    exp_x = np.exp(x - np.max(x, axis=axis, keepdims=True))
    return exp_x / np.sum(exp_x, axis=axis, keepdims=True)

In [6]:
# Apply self-attention
output = self_attention(input_sequence)
print("Output after self-attention:")
print(output)


Output after self-attention:
[[ 0.3080962   1.67488102 -7.23909351 10.31366241]
 [ 0.25418713  1.47595752 -7.71230413 11.67042054]
 [ 0.23733588  1.41377673 -7.86022335 12.09452473]]


# Example using self-attention on a sentence


In [7]:
import numpy as np
import nltk
from nltk.tokenize import word_tokenize
import gensim.downloader as api

In [8]:
# Download GloVe embeddings (you can choose other pre-trained word embeddings as well)
word_vectors = api.load("glove-wiki-gigaword-100")

[==================================================] 100.0% 128.1/128.1MB downloaded


In [9]:
def sentence_to_embeddings(sentence):
    tokens = word_tokenize(sentence.lower())  # Tokenize the sentence
    embeddings = []  # List to store word embeddings

    for token in tokens:
        if token in word_vectors:
            embeddings.append(word_vectors[token])  # If word is in vocabulary, retrieve its embedding
        else:
            embeddings.append(np.zeros(word_vectors.vector_size))  # If word is out-of-vocabulary, use zero vector

    return np.array(embeddings)

In [10]:
def self_attention(input_sequence):
    # Step 1: Calculate Query, Key, and Value matrices
    Q = np.dot(input_sequence, W_q)  # Transform input embeddings to Query space
    K = np.dot(input_sequence, W_k)  # Transform input embeddings to Key space
    V = np.dot(input_sequence, W_v)  # Transform input embeddings to Value space

    # Step 2: Calculate attention scores
    scores = np.dot(Q, K.T) / np.sqrt(d_k)  # Scaled dot product attention
    attention_weights = softmax(scores, axis=1)  # Apply softmax to obtain attention weights

    # Step 3: Apply attention weights to Value vectors
    attention_output = np.dot(attention_weights, V)  # Weighted sum of Value vectors

    return attention_output

In [11]:
# Example weight matrices (learnable parameters)
W_q = np.random.randn(word_vectors.vector_size, word_vectors.vector_size)  # Query matrix
W_k = np.random.randn(word_vectors.vector_size, word_vectors.vector_size)  # Key matrix
W_v = np.random.randn(word_vectors.vector_size, word_vectors.vector_size)  # Value matrix


In [12]:
# Dimension of Key and Query vectors
d_k = W_q.shape[1]

In [13]:
# Softmax function
def softmax(x, axis=-1):
    exp_x = np.exp(x - np.max(x, axis=axis, keepdims=True))
    return exp_x / np.sum(exp_x, axis=axis, keepdims=True)

In [14]:
# Example sentence
sentence = "The quick brown fox jumps over the lazy dog."

In [19]:
# Convert sentence to embeddings
input_sequence = sentence_to_embeddings(sentence)

In [20]:
# Apply self-attention
output = self_attention(input_sequence)
print("Output after self-attention:")
print(output)


Output after self-attention:
[[ 10.5383473   -6.81568139   0.54388586  -8.26105457  -6.48654902
    5.09520138   0.23069278   4.053301    -6.82900357   0.76474214
    4.81274024   8.90122573  -9.28262123   4.38876221  -6.52846012
   -1.24772382   8.36558712  -7.25393221  -0.30997645   3.46245024
   -3.70074296  -2.01920212  12.53209955   6.29604624  -2.32583125
    0.07558988  -3.33037453  -3.92278944  -3.20000669   8.59858666
    1.1533959   -0.53729564   1.39028093   0.2033916   -7.94427866
   -5.68902002   2.86276108  -5.41374109  -3.00488356   2.79683913
   -6.78621478   0.84170686  -1.25506141   2.98129747  -7.46694073
   -3.00169229   5.1258942   -2.54199045  -4.90104911   0.72238951
   -0.83379572   2.29747668  -3.05484212  -1.53502808   1.1568491
   -3.31387894  -5.25424941  -3.98067153  -2.2340476   -0.92174951
   -0.35875352   0.66528344  -2.30993801  -5.6229472    7.50359115
    7.57086726   4.82810394 -10.96710376   4.29291668   5.06484236
    3.6850362   -6.11842411   7.56